# Generated by Django 6.0.1 on 2026-01-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('pg', 'PG / Hostel'), ('mess', 'Mess / Tiffin'), ('medical', 'Medical Store'), ('stationery', 'Stationery')], max_length=20)),
                ('gstin', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('open_24_hours', models.BooleanField(default=False)),
                ('working_days', models.JSONField(default=list)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BusinessRequest',
        ),
    ]
