# Generated by Django 6.0.1 on 2026-01-17 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='place',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='place',
            name='open_24_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='working_days',
            field=models.JSONField(default=list, help_text="Example: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']"),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('pg', 'PG / Hostel'), ('mess', 'Mess / Tiffin'), ('medical', 'Medical Store'), ('stationery', 'Stationery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['category'], name='locations_p_categor_a07adf_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['is_verified'], name='locations_p_is_veri_754f86_idx'),
        ),
    ]
