# Generated by Django 6.0.1 on 2026-01-23 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_business_phone'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='business',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='business.business'),
        ),
    ]
